version: '3.8'

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      # context: ./dockerfiles 因為 nginx.dockerfile 有用到 COPY src ., 但 src 不在 /dockerfiles 下所以找不到
      # dockerfile: nginx.dockerfile
      context: . 
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes: # 透過 mount 將 local file 映射到 container, 方便開發
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: # 透過 mount 將 local file 映射到 container, 方便開發
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: # 透過 mount 將 local file 映射到 container, 方便開發
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: # 透過 mount 將 local file 映射到 container, 方便開發
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm: # 可以在裡面寫類似 Dockerfile 內容, 這樣就不用寫 Dockerfile, 但感覺還是寫 Dockerfile 和 docker-compose 邏輯分開比較好
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes: # 透過 mount 將 local file 映射到 container, 方便開發
      - ./src:/var/www/html
